spring:
  applicaton:
    name: admin-service
  cloud:
    kubernetes:
      catalog-services-watch:
        enabled: true
        catalogServicesWatchDelay: 5000
      discovery:
        namespace: carloszamo077-2-dev
      client:
        namespace: carloszamo077-2-dev
        
management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 8081